Hotfix

diff --git a/resources/aurhandler b/resources/aurhandler
--- a/resources/aurhandler
+++ b/resources/aurhandler
@@ -6,7 +6,25 @@ source /etc/lemon/resources/lemonlib
 #  AUR package installation logic. This should be in lemonlib as a function, but doesn't work when I put it there because Brian Fox is a fucking sadist.
 #  Bash script exists to teach us all a lesson in humility.
 #
-function aurdephandler {
+
+mkdir $HOME/.aurtool
+cd $HOME/.aurtool
+git clone http://aur.archlinux.org/$@.git
+cd $@
+PKGB=./PKGBUILD
+if [ ! -f $PKGB ]; then
+  echo "ERROR: Package $@ does not exist!"
+  echo "Failed AUR package: $@ (invalid package name)" >> /home/aur/aur.log
+  cd /home/aur
+  exit 1
+else
+  if isyes "Would you like to edit the PKGBUILD? (Y/n)"; then
+    if which nano &> /dev/null; then
+      nano ./PKGBUILD
+    else
+      vim ./PKGBUILD
+    fi
+  fi
   unset makedepends
   unset optdepends
   unset depends
@@ -27,39 +45,22 @@ function aurdephandler {
         if ! aurhandler $i; then
           echo "Unable to install dependency $i!"
           echo "Failed AUR package: $@ (failed to install dependency)" >> /home/aur/aur.log
+          cd /home/aur
           exit 1
         fi
       fi
     fi
   done
-}
-
-mkdir $HOME/.aurtool
-cd $HOME/.aurtool
-git clone http://aur.archlinux.org/$@.git
-cd $@
-PKGB=./PKGBUILD
-if [ ! -f $PKGB ]; then
-  echo "ERROR: Package $@ does not exist!"
-  echo "Failed AUR package: $@ (invalid package name)" >> /home/aur/aur.log
-  exit 1
-else
-  if isyes "Would you like to edit the PKGBUILD? (Y/n)"; then
-    if which nano &> /dev/null; then
-      nano ./PKGBUILD
-    else
-      vim ./PKGBUILD
-    fi
-  fi
-  aurdephandler
   if ! (makepkg -cs); then
     echo "ERROR: Package $@ failed to build!"
     echo "Failed AUR package: $@ (build failure)" >> /home/aur/aur.log
+    cd /home/aur
     exit 1
   else
     sudo pacman -U --noconfirm *.pkg.tar*
   fi
   rm -rf $HOME/.aurtool
+  cd /home/aur
   exit 0
 fi
 
