Update aurhandler

diff --git a/resources/aurhandler b/resources/aurhandler
--- a/resources/aurhandler
+++ b/resources/aurhandler
@@ -6,26 +6,50 @@ source /etc/lemon/resources/lemonlib
 #  AUR package installation logic. This should be in lemonlib as a function, but doesn't work when I put it there because Brian Fox is a fucking sadist.
 #  Bash script exists to teach us all a lesson in humility.
 #
+#  edit: still didn't work. It's now a copy-paste from aurtool because reasons. 
 
-for b in ${@}; do
-  mkdir $HOME/.aurtool
-  cd $HOME/.aurtool
-  git clone http://aur.archlinux.org/$b.git
-  cd $b
-  PKGB=./PKGBUILD
-  if [ ! -f $PKGB ]; then
-    echo "ERROR: Package $b does not exist!"
-    echo "Failed AUR package: $b (invalid package name)" >> /home/aur/aur.log
-    cd /home/aur
-    return 1
-  else
-    if isyes "Would you like to edit the PKGBUILD? (Y/n)"; then
+OP=$1
+
+if [ "$OP" == -S ]; then
+  if [ -z ${@:2} ]; then
+    echo "Error: -S requires additional input."
+    echo "aurtool --help for help page"
+    exit 1
+  fi
+  for b in ${@:2}; do
+    cd $HOME
+    mkdir .aurtool
+    cd .aurtool
+    git clone http://aur.archlinux.org/$b.git
+    cd $b
+    PKGB=./PKGBUILD
+    if [ ! -f $PKGB ]; then
+      echo "Error: package does not exist by the name $b!"
+      echo "Aborting"
+      exit 1
+    fi
+    #
+    # Yes, this is a pointless function that uses up 3 lines unnecessarily. The script didn't behave properly without it. Bash has moods, and Brian Fox hates us all.
+    #
+    function PKGBUILD {
+    if isyes "Would you like to edit the PKGBUILD? (Y/n)" ; then
       if which nano &> /dev/null; then
         nano ./PKGBUILD
       else
-        vim ./PKGBUILD
+        if which vim &> /dev/null; then
+          vim ./PKGBUILD
+        else
+          echo "No suitable text editor found!"
+          echo "If one is present on the system, enter its command now (eg: nano, vim, emacs, etc). Otherwise leave blank to skip PKGBUILD editing."
+          read PKGEDIT
+          if [ -v $PKGEDIT ]; then 
+            $PKGEDIT ./PKGBUILD
+          fi
+        fi
       fi
     fi
+    }
+    PKGBUILD
     unset makedepends
     unset optdepends
     unset depends
@@ -39,30 +63,31 @@ for b in ${@}; do
     done
     for i in ${DEPS[@]}; do
       if ! pacman -Ql $i &> /dev/null; then
-        echo "Trying to install $i with pacman (dependency)..."
+        echo "Trying to install $i with pacman (dependency)"
         if ! sudo pacman -S --noconfirm --needed $i; then
-          echo "Installing $i with pacman failed!"
-          echo "Trying to install $i from AUR..."
-          if ! aurhandler $i; then
-            echo "Unable to install dependency $i!"
-            echo "Failed AUR package: $@ (failed to install dependency)" >> /home/aur/aur.log
-            cd /home/aur
-            return 1
+          echo "Installing $i with pacman failed"
+          echo "Trying to install $i from AUR"
+          if ! NODEL=1 aurtool -S $i; then
+            echo "FATAL: Unable to install dependency $i!"
+            exit 1
           fi
         fi
       fi
     done
-    if ! (makepkg -cs); then
-      echo "ERROR: Package $b failed to build!"
-      echo "Failed AUR package: $b (build failure)" >> /home/aur/aur.log
-      cd /home/aur
-      return 1
-    else
-      sudo pacman -U --noconfirm *.pkg.tar*
+    if ! makepkg -csi; then
+      echo "Error! Aborting"
+      cd $HOME
+      exit 1
     fi
-    rm -rf $HOME/.aurtool
-    cd /home/aur
-    return 0
+    cd $HOME/.aurtool
+  done
+  if [ -z "$NODEL" ]; then
+    NODEL="1"
   fi
-done
-
+  if [ ! "$NODEL" == 1 ]; then
+    if isyes "Build files and / or built packages are stored in .aurtool in your home directory. Would you like to delete them? (Y/n)"; then
+      echo "Cleaning up.."
+      rm -rf $HOME/.aurtool
+    fi
+  fi
+fi
