Small bug fix
Arch changed the package title of refind from refind-efi to simply refind. This has now been corrected. 

An error check has also been added to refind package fetching so that it's correctly logged if it fails for any reason.

diff --git a/resources/lemonaid b/resources/lemonaid
--- a/resources/lemonaid
+++ b/resources/lemonaid
@@ -141,7 +141,9 @@ function BOOT {
     ln -s /hostlvm /run/lvm
   fi
   if [ $REFIND == 1 ] && [ $BOOTMODE == 0 ]; then
-    pacman -S --needed --noconfirm refind-efi
+    if ! pacman -S --needed --noconfirm refind; then
+      echo "Failed to fetch refind!" >> /tmp/lemonaid.log
+    fi
     if ! refind-install; then
       echo "Refind install failed!" >> /tmp/lemonaid.log
     fi
